export enum ErrorCode {
  GENERIC = 'GENERIC',
  GENERIC_NOT_AUTHORIZED = 'GENERIC_NOT_AUTHORIZED',
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  PRODUCT_ALREADY_EXISTS = 'PRODUCT_ALREADY_EXISTS',
  PRODUCT_HAVE_STOCK = 'PRODUCT_HAVE_STOCK'
}
